# Generated by Django 3.2.4 on 2021-06-21 21:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stickers', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='caixastickers',
            name='data_venda',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='caixastickers',
            name='valor_unidade',
            field=models.FloatField(default=0),
        ),
    ]
