# Generated by Django 3.2.4 on 2021-06-22 01:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stickers', '0002_auto_20210621_1655'),
    ]

    operations = [
        migrations.AddField(
            model_name='caixastickers',
            name='valor_total',
            field=models.FloatField(default=0),
        ),
    ]
