# Generated by Django 3.2.4 on 2021-06-22 01:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stickers', '0003_caixastickers_valor_total'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='caixastickers',
            name='valor_total',
        ),
    ]
