# Generated by Django 3.2.4 on 2021-06-23 22:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stickers', '0005_caixastickers_valor_total'),
    ]

    operations = [
        migrations.AlterField(
            model_name='caixastickers',
            name='valor_unidade',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
