# Generated by Django 3.2.4 on 2021-07-10 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stickers', '0008_totalstickers'),
    ]

    operations = [
        migrations.AlterField(
            model_name='totalstickers',
            name='total_vendidos',
            field=models.IntegerField(null=True),
        ),
    ]
