# Generated by Django 3.2.4 on 2021-07-11 03:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stickers', '0010_alter_totalstickers_total_vendidos'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='totalstickers',
            name='total_vendidos',
        ),
        migrations.AddField(
            model_name='totalstickers',
            name='stickers_total',
            field=models.IntegerField(default=0),
        ),
    ]
