# Generated by Django 3.2.4 on 2021-07-11 18:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stickers', '0011_auto_20210710_2247'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CaixaStickers',
            new_name='CaixaSticker',
        ),
        migrations.RenameModel(
            old_name='TotalStickers',
            new_name='TotalSticker',
        ),
    ]
